import "./index.css";

const app = document.querySelector("#root");
const FALCON_MARK = "/manus-storage/adya-vigil-falcon-mark-bright_82d40bc4.png";
const HERO_IMAGE = "/manus-storage/adya-vigil-hero_37ec0d65.png";
const EVIDENCE_IMAGE = "/manus-storage/adya-vigil-evidence_8a34263b.png";
const PATTERN_IMAGE = "/manus-storage/adya-vigil-pattern_f877bdd0.png";
const demoPreview = new URLSearchParams(window.location.search).get("demo") === "1";
const state = { type: "url", value: "", label: "", result: null, fileId: null, uploading: false, demo: demoPreview, demoSamplesOpen: demoPreview, pipeline: ["Waiting for input", "Structural checks", "Evidence weighting", "Guidance generated"], pipelineStep: 0, stats: null, scans: [] };
const navItems = [{ href: "/", label: "Dashboard", icon: "◉" }, { href: "/how-it-works", label: "How it works", icon: "◇" }, { href: "/scan", label: "Scan center", icon: "⌁" }, { href: "/history", label: "Scan history", icon: "◷" }, { href: "/about", label: "About model", icon: "ⓘ" }];
const scanTypes = [{ id: "url", label: "URL", icon: "↗" }, { id: "email", label: "Email", icon: "✉" }, { id: "sms", label: "SMS", icon: "▣" }, { id: "qr", label: "QR image", icon: "⌗" }];
const demoExamples = [
  { id: "safe-url", type: "url", risk: "low", label: "Demo · low-risk URL", value: "https://www.example.com/security-center" },
  { id: "safe-email", type: "email", risk: "low", label: "Demo · low-risk email", value: "From: team@example.com\nSubject: Weekly project update\n\nThe project review is scheduled for Thursday. No action is required before the meeting." },
  { id: "risk-url", type: "url", risk: "high", label: "Demo · high-risk URL", value: "http://secure-wallet.example.top/login?verify=1&next=javascript:eval(document.cookie)" },
  { id: "risk-email", type: "email", risk: "high", label: "Demo · high-risk email", value: "From: billing-alert@secure-payments.example\nSubject: URGENT payment failed\n\nClick the bit.ly link immediately to verify your card, password, and one-time passcode or your account will be suspended." },
];

function esc(value = "") { return String(value).replace(/[&<>\"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#039;" }[char])); }
function authHeaders() { try { const raw = sessionStorage.getItem("manus-cookie"); if (raw) { const pair = raw.split(";").find(s => s.trim().startsWith("manus_session=")); const token = pair?.trim().slice("manus_session=".length); if (token) return { Authorization: `Bearer ${token}` }; } } catch {} return {}; }
async function rpc(path, input, method = "GET") { const options = { method, credentials: "include", headers: { ...authHeaders() } }; if (method === "GET") options.headers.accept = "application/json"; else { options.headers["content-type"] = "application/json"; options.body = JSON.stringify({ json: input }); } const url = method === "GET" ? `/api/trpc/${path}?input=${encodeURIComponent(JSON.stringify({ json: input }))}` : `/api/trpc/${path}`; const response = await fetch(url, options); const payload = await response.json(); if (!response.ok || payload.error) throw new Error(payload.error?.json?.message || payload.error?.message || "Request failed"); return payload.result?.data?.json ?? payload[0]?.result?.data?.json ?? payload; }
async function loadData() { try { state.stats = await rpc("scans.stats", null); state.scans = await rpc("scans.list", { limit: 100 }); } catch { state.stats = state.stats || { total: 0, highRisk: 0, mediumRisk: 0, lowRisk: 0, averageScore: 0 }; state.scans = state.scans || []; } }

function analyze(type, raw, label) {
  const value = raw.trim(); const lower = value.toLowerCase(); const findings = []; const add = (title, detail, weight, tone = "medium") => findings.push({ title, detail, weight, tone });
  if (!value) add("No signal provided", "Add a URL, message, or sender content so the model can inspect it.", 0, "low");
  if (type === "url" || type === "qr") {
    try {
      const url = new URL(value.includes("://") ? value : `https://${value}`);
      if (url.protocol !== "https:") add("Unencrypted destination", "The destination does not use HTTPS, so traffic can be exposed or altered in transit.", 22, "high");
      if (url.hostname.split(".").length > 3) add("Deep subdomain chain", "Multiple subdomains can make a lookalike destination harder to spot.", 14);
      if (/xn--|%[0-9a-f]{2}|@/.test(value)) add("Obfuscated URL structure", "Encoded characters or an @ symbol can conceal the real destination.", 24, "high");
      if (/\.(zip|mov|top|click|work|support|gq|tk)(\/|$)/.test(url.hostname + url.pathname)) add("Malicious URL pattern", "This domain or path uses a pattern frequently seen in disposable phishing campaigns.", 24, "high");
      if (/(login|verify|secure|update|wallet|invoice|refund|payment|gift|confirm)/.test(lower)) add("Credential or payment lure", "The destination language points toward a sensitive action that attackers commonly imitate.", 20, "high");
      if (/^(javascript:|data:)|<script|eval\(|document\.cookie|onclick=|onerror=/.test(lower)) add("Weak JavaScript pattern", "The payload contains script-like or browser-execution markers that can be used to redirect, steal session data, or bypass user expectations.", 32, "high");
      if (!findings.length) add("No strong heuristic flags", "The URL structure does not match the strongest local warning patterns. Still verify the domain before proceeding.", 4, "low");
    } catch { add("Malformed URL", "This does not parse as a normal web address. Do not open it until the destination is verified.", 28, "high"); }
  } else {
    if (/(urgent|immediately|within \d+ hours|last chance|final notice|act now)/.test(lower)) add("Urgency pressure", "The message compresses your decision window and discourages careful verification.", 20, "high");
    if (/(password|passcode|otp|one[- ]time|verification code|social security|bank|card|payment)/.test(lower)) add("Sensitive-data request", "The message references credentials, financial details, or codes that should not be shared from an unsolicited message.", 26, "high");
    if (/(click|tap|open|download|confirm|verify|sign in|login)/.test(lower)) add("Action request", "It asks you to follow a link, open a file, or confirm an account action.", 16, "medium");
    if (/(bit\.ly|tinyurl|t\.co|goo\.gl|is\.gd|\.zip|\.html?)/.test(lower)) add("Redirect or attachment marker", "Short links and executable-looking attachments hide where the action leads.", 18, "high");
    if (/@[a-z0-9.-]+\.[a-z]{2,}/.test(value) && type === "email") add("Sender context needs verification", "A familiar-looking sender address is not proof of authenticity; verify it through a known channel.", 9, "medium");
    if (/script|javascript|eval\(|document\.cookie|onclick=/.test(lower)) add("Weak JavaScript pattern", "The content references browser-execution behavior that can be abused to redirect a user or expose session data.", 26, "high");
    if (!findings.length) add("Low-signal content", "No common pressure, payment, credential, or link indicators were found in this sample.", 5, "low");
  }
  const score = Math.min(99, Math.max(3, findings.reduce((sum, item) => sum + item.weight, 0)));
  const verdict = score >= 70 ? "High risk" : score >= 40 ? "Needs caution" : "Low signal";
  const summary = score >= 70 ? "Multiple indicators suggest you should treat this as a likely phishing attempt." : score >= 40 ? "The sample contains warning signals that merit independent verification." : "The local model found limited warning signals, but no heuristic scan can prove a message is safe.";
  const nextSteps = score >= 70 ? ["Do not click, reply, download, or scan again.", "Verify through a known-good website, app, or phone number.", "Report the message to your provider and delete it."] : score >= 40 ? ["Pause before taking the requested action.", "Check the sender and destination using a trusted channel.", "Do not share credentials, codes, or payment details."] : ["Confirm the domain or sender independently before proceeding.", "Keep software and browser protections enabled.", "If the context feels unexpected, treat it as suspicious."];
  return { score, verdict, summary, findings, nextSteps, label: label || `${type.toUpperCase()} sample` };
}

function shell(content) { const path = window.location.pathname; return `<div class="app-shell"><aside class="sidebar"><a class="brand" href="/"><span class="brand-mark"><img src="${FALCON_MARK}" alt="Falcon shield mark" /></span><span><b>ADYA</b><em>VIGIL AI</em></span></a><div class="rail-label">Security desk / 0.9.4</div><nav class="nav-stack">${navItems.map(item => `<a href="${item.href}" class="nav-item ${path === item.href ? "active" : ""}"><span class="nav-icon">${item.icon}</span><span>${item.label}</span>${path === item.href ? "<strong>›</strong>" : ""}</a>`).join("")}</nav><div class="sidebar-spacer"></div><div class="rail-status"><span class="status-dot"></span> Local model online<div class="mono">RULESET 0.9.4 · READY</div></div><div class="sidebar-foot">⌁ Your content stays in this workspace</div></aside><main class="workspace">${content}</main></div>`; }
function pageHeader(kicker, title, desc, action = "") { return `<header class="page-header"><div><div class="eyebrow"><span class="signal-line"></span>${kicker}</div><h1>${title}</h1><p>${desc}</p></div>${action}</header>`; }
function shieldViz() { return `<div class="shield-viz"><div class="shield-grid"></div><div class="shield-core"><img src="${FALCON_MARK}" alt="Animated falcon shield" /></div><span class="orbit orbit-a"></span><span class="orbit orbit-b"></span><span class="viz-scan-beam"></span><span class="viz-label mono">LIVE SIGNAL SWEEP</span></div>`; }
function teamMasthead() { return `<div class="team-masthead"><span class="gold-spark spark-one">✦</span><span class="gold-spark spark-two">✧</span><span class="gold-spark spark-three">⋆</span><div class="team-kicker"><span class="team-rule"></span><span class="mono">ADYA VIGIL AI · SECURITY DESK</span><span class="team-rule"></span></div><h2>THE FALCON CODERS</h2><p>BUILDING CLARITY IN THE SIGNAL</p></div>`; }
function dashboard() { const stats = state.stats || { total: 0, highRisk: 0, mediumRisk: 0, averageScore: 0 }; return shell(`<section class="page-wrap">${teamMasthead()}${pageHeader("DASHBOARD / SECURITY POSTURE", "Your signal desk.", "A live command surface for the suspicious links, messages, and QR payloads your workspace has inspected.", `<a href="/scan" class="button primary">⌁ New scan <span>↗</span></a>`)}<div class="cyber-banner"><div>${shieldViz()}</div><div><span class="mono">CURRENT WORKSPACE POSTURE</span><div class="posture-score"><strong>${stats.averageScore ?? 0}</strong><span>/100 avg risk</span></div><p>${stats.highRisk ? `${stats.highRisk} high-risk signal${stats.highRisk === 1 ? "" : "s"} need attention.` : "No high-risk signals recorded yet."}</p><div class="telemetry"><span>MODEL UPTIME 99.8%</span><span>ENCRYPTED SESSION</span></div></div></div><div class="posture-grid"><div class="stat-card"><span class="mono">TOTAL SCANS</span><strong>${stats.total ?? 0}</strong><span>Persisted to database</span></div><div class="stat-card danger"><span class="mono">HIGH RISK</span><strong>${stats.highRisk ?? 0}</strong><span>Review before acting</span></div><div class="stat-card caution"><span class="mono">CAUTION</span><strong>${stats.mediumRisk ?? 0}</strong><span>Verify independently</span></div></div><div class="dashboard-columns"><div class="paper-card activity-card"><div class="panel-head"><div><span class="mono">RECENT ACTIVITY / PERSISTED</span><h2>Latest scans</h2></div><a href="/history" class="text-link">View all ↗</a></div>${state.scans?.length ? state.scans.slice(0, 5).map(scan => activityRow(scan)).join("") : `<div class="empty-state"><span class="pulse-dot"></span><p>No scans yet. Start by checking a suspicious signal.</p><a href="/scan" class="text-link">Open scan center ↗</a></div>`}</div><div class="evidence-card"><img src="${EVIDENCE_IMAGE}" alt="Abstract phishing evidence" /><div><span class="mono">MODEL NOTE / DEFENSE IN DEPTH</span><h3>Fast answers deserve visible evidence.</h3><p>Risk scores are guidance, not proof. Use trusted channels to verify any unexpected request.</p></div></div></div></section>`); }
function activityRow(scan) { const tone = scan.score >= 70 ? "danger" : scan.score >= 40 ? "caution" : "safe"; return `<div class="activity-row"><div class="activity-icon ${tone}">${scan.inputType === "url" ? "↗" : scan.inputType === "email" ? "✉" : scan.inputType === "sms" ? "▣" : "⌗"}</div><div><b>${esc(scan.inputLabel)}</b><span>${scan.inputType.toUpperCase()} · ${new Date(scan.createdAt).toLocaleString()}</span></div><strong class="${tone}-text">${scan.score}</strong></div>`; }
function scanPage() {
  const types = scanTypes.map(item => `<button data-type="${item.id}" class="type-tab ${state.type === item.id ? "selected" : ""}"><span>${item.icon}</span>${item.label}</button>`).join("");
  const trace = state.pipeline.map((step, index) => `<div class="trace-step ${index <= state.pipelineStep ? "done" : ""} ${index === state.pipelineStep ? "current" : ""}"><span>${index <= state.pipelineStep ? "✓" : "0" + (index + 1)}</span><div><b>${step}</b><small>${index === 0 ? "Input received" : index === 1 ? "Domain, sender, and syntax pass" : index === 2 ? "Signals weighted against ruleset" : "Plain-language response ready"}</small></div></div>`).join("");
  const demoTrace = state.demo ? `<div class="demo-trace"><div class="trace-head"><span class="mono">DEMO MODE / MODEL TRACE</span><span class="live-chip">LIVE</span></div>${trace}</div>` : `<div class="demo-callout"><span class="mono">MODEL VISIBILITY</span><b>Turn on demo mode to watch each check happen.</b><p>The trace is illustrative; the final score still comes from the live local ruleset.</p></div>`;
  const samplePicker = state.demo ? `<button id="sample-toggle" type="button" class="sample-toggle" aria-expanded="${state.demoSamplesOpen}"><span>⌄</span>${state.demoSamplesOpen ? "Hide demo samples" : "Show demo samples"}</button>${state.demoSamplesOpen ? `<div class="sample-picker"><div class="sample-picker-head"><span class="mono">PASTE-READY SAMPLES</span><span>2 HIGH · 2 LOW</span></div><div class="sample-grid">${demoExamples.map((example, index) => `<button type="button" class="sample-card ${example.risk}" data-sample="${example.id}"><span class="sample-card-meta"><span>${example.type.toUpperCase()} ${String(index + 1).padStart(2, "0")}</span><b>${example.risk === "high" ? "HIGH RISK" : "LOW RISK"}</b></span><span class="sample-card-value">${esc(example.value)}</span><span class="sample-card-action">Paste into field ↗</span></button>`).join("")}</div></div>` : ""}` : "";
  const fieldLabel = state.type === "url" ? "URL or domain" : state.type === "email" ? "Sender, subject, and body" : state.type === "sms" ? "Message content" : "Decoded QR payload or context";
  const qr = state.type === "qr" ? `<div class="upload-zone"><span class="upload-icon">⇧</span><div><b>${state.uploading ? "Uploading to secure storage…" : "Upload a QR image"}</b><small>PNG, JPG, WEBP, or GIF · max 5 MB</small></div><input id="qr-file" type="file" accept="image/png,image/jpeg,image/webp,image/gif" /></div>` : "";
  return shell(`<section class="page-wrap">${pageHeader("SCAN CENTER / LIVE ANALYSIS", `Check the signal<br><i>before you follow it.</i>`, "Paste a suspicious URL, email, SMS, or QR payload. ADYA VIGIL AI turns raw content into an explainable risk posture.", `<div class="header-meta"><span class="online-pill"><span class="status-dot"></span> Engine ready</span><label class="switch-row"><span>Demo trace</span><input id="demo-toggle" type="checkbox" ${state.demo ? "checked" : ""} /><span class="switch"></span></label></div>`)}<div class="scan-layout single-scan"><div class="scan-panel paper-card ${state.result ? "has-result" : ""}"><div class="panel-head"><div><span class="mono">01 / INPUT SIGNAL</span><h2>What do you want to inspect?</h2></div><span class="panel-glyph">⌬</span></div><div class="type-tabs">${types}</div><label class="field-label">Optional label <span>for scan history</span></label><input id="label" class="input" value="${esc(state.label)}" placeholder="e.g. Invoice email from unknown sender" /><div id="scan-box" class="scan-box"><div class="scan-box-grid"></div><span class="scan-target">⌁</span><span class="scan-beam"></span><label class="field-label">${fieldLabel}</label>${qr}<textarea id="value" class="textarea" placeholder="${state.type === "url" ? "https://example.com/account/verify" : "Paste the complete content here…"}">${esc(state.value)}</textarea>${samplePicker}</div><div class="scan-actions"><button id="analyze" class="button primary" ${state.uploading || !state.value.trim() ? "disabled" : ""}>${state.result ? "Run again" : "Analyze signal"} <span>↗</span></button><span class="mono">LOCAL HEURISTICS · EXPLAINABLE</span></div></div></div>${state.result ? resultCard(state.result) : ""}</section>`);
}

function howItWorksPage() {
  const stages = [
    ["01", "Capture the signal", "Paste a URL, email, SMS, or QR payload. The content is kept in this workspace while the scan runs."],
    ["02", "Inspect structure", "The model checks domains, protocols, sender context, syntax, redirects, and browser-execution markers."],
    ["03", "Weight evidence", "Each matching signal contributes a visible weight to the score instead of disappearing behind a black-box verdict."],
    ["04", "Explain the posture", "The result pairs the score with plain-language findings and a practical next-step playbook."],
  ];
  return shell(`<section class="page-wrap">${pageHeader("HOW IT WORKS / MODEL VISIBILITY", `See the signal<br><i>behind the score.</i>`, "ADYA VIGIL AI is designed to make phishing analysis understandable: inspect the structure, show the evidence, and give the user a safer next move.", `<a href="/scan" class="button primary">Open scan center <span>↗</span></a>`)}<div class="how-hero"><div>${shieldViz()}</div><div><span class="mono">LOCAL HEURISTICS · EXPLAINABLE</span><h2>Evidence, not a black box.</h2><p>The scanner uses deterministic rules to identify common phishing patterns. It does not claim that a low score proves a message is safe; it shows what the local ruleset noticed so a person can verify the context independently.</p><div class="how-pills"><span>Visible evidence</span><span>Weighted signals</span><span>Safer next steps</span></div></div></div><div class="stage-grid">${stages.map(stage => `<article class="stage-card"><span class="stage-number">${stage[0]}</span><span class="mono">MODEL STAGE</span><h3>${stage[1]}</h3><p>${stage[2]}</p></article>`).join("")}</div><div class="how-columns"><div class="paper-card"><span class="mono">SIGNALS WE CHECK</span><h2>What moves the score?</h2><div class="signal-list"><div><b>Pressure language</b><span>Urgency and forced action requests that reduce time for verification.</span></div><div><b>Credential or payment lure</b><span>Requests for passwords, codes, cards, payments, or sensitive details.</span></div><div><b>URL and redirect structure</b><span>Unencrypted destinations, risky patterns, deep subdomains, encoded values, and short links.</span></div><div><b>Weak JavaScript markers</b><span>Script-like content that may redirect users or expose browser session data.</span></div></div></div><div class="paper-card guidance-card"><span class="mono">AFTER THE SCORE</span><h2>What should the user do next?</h2><p>Pause before clicking, replying, downloading, or paying. Verify the sender or destination through a known-good channel, and report unexpected requests to the relevant provider.</p><a href="/scan" class="text-link">Run your own signal check ↗</a></div></div></section>`);
}

function resultCard(result) { const tone = result.score >= 70 ? "danger" : result.score >= 40 ? "caution" : "safe"; return `<section class="result-card ${tone} score-reveal"><div class="result-top"><div><span class="mono">03 / MODEL VERDICT / ${new Date().toLocaleTimeString()}</span><div class="verdict-row"><span class="verdict-icon">${tone === "danger" ? "!" : tone === "caution" ? "△" : "✓"}</span><h2>${result.verdict}</h2></div><p>${result.summary}</p></div><div class="score-orbit"><div class="score-ring" style="--score:${result.score * 3.6}deg;--score-color:${tone === "danger" ? "#ff5b5b" : tone === "caution" ? "#ffbf4a" : "#a7f432"}"><div><strong>${result.score}</strong><span>/100</span></div></div><span class="orbit orbit-a"></span><span class="orbit orbit-b"></span></div></div><div class="result-columns"><div><span class="mono">DETECTION REASONS / WEIGHTED SIGNALS</span>${result.findings.map(f => `<div class="finding"><span class="finding-dot ${f.tone}"></span><div><b>${esc(f.title)}</b><p>${esc(f.detail)}</p></div><strong>+${f.weight}</strong></div>`).join("")}</div><div class="next-steps"><span class="mono">WHAT TO DO NEXT / PLAYBOOK</span>${result.nextSteps.map((step, i) => `<div class="step"><span>0${i + 1}</span><p>${esc(step)}</p></div>`).join("")}<div class="safety-note"><span>⌁</span><p>Never treat a heuristic score as proof of safety. Validate unexpected requests through a known-good channel.</p></div></div></div></section>`; }
function historyPage() { return shell(`<section class="page-wrap">${pageHeader("HISTORY / PERSISTED RECORDS", "Every signal, kept clear.", "Review stored results, evidence, and the reasoning behind each model verdict.") }<div class="paper-card table-card"><div class="table-head"><span class="mono">${state.scans?.length ?? 0} SAVED RECORDS</span><span class="mono">DATABASE / UTC → LOCAL</span></div>${state.scans?.length ? state.scans.map(activity => `<div class="history-row">${activityRow(activity)}<span class="history-verdict">${esc(activity.verdict)}</span></div>`).join("") : `<div class="empty-state"><span class="pulse-dot"></span><p>Your persisted scan history will appear here.</p></div>`}</div></section>`); }
function aboutPage() { return shell(`<section class="page-wrap">${pageHeader("ABOUT / ADYA VIGIL AI", `A clearer moment<br><i>before the click.</i>`, "An explainable phishing-signal desk for URLs, emails, SMS messages, and QR payloads.") }<div class="about-grid"><div class="paper-card about-copy"><span class="mono">THE MODEL IN PLAIN LANGUAGE</span><h2>Watchful. Lucid. Grounded.</h2><p>The working model uses deterministic local heuristics to inspect urgency pressure, sensitive-data requests, action prompts, redirect patterns, obfuscated URLs, suspicious domains, and weak JavaScript markers.</p><p>It is intentionally transparent. A score is never presented alone: each result includes the reasons that moved the score and practical next steps to reduce exposure.</p><div class="principles"><div><b>01</b><span><strong>Explainable</strong>Every finding is readable and tied to a visible input signal.</span></div><div><b>02</b><span><strong>Persistent</strong>Results and uploaded QR metadata are saved to the workspace database and storage.</span></div><div><b>03</b><span><strong>Practical</strong>Guidance focuses on what to do next, not just what went wrong.</span></div></div></div><div class="about-side"><div class="pattern-card"><img src="${PATTERN_IMAGE}" alt="Abstract signal pattern" /><div class="pattern-overlay"><img src="${FALCON_MARK}" alt="Falcon shield mark" /><span class="mono">FALCON WATCH / ADYA VIGIL AI</span></div></div><div class="quote-card"><span>?</span><p>“A suspicious sender is not proof of harm. Here is the evidence we found.”</p></div></div></div></section>`); }

function render() { const path = window.location.pathname; app.innerHTML = path === "/scan" ? scanPage() : path === "/how-it-works" ? howItWorksPage() : path === "/history" ? historyPage() : path === "/about" ? aboutPage() : dashboard(); bind(); }
function bind() { document.querySelectorAll("a[href]").forEach(anchor => anchor.addEventListener("click", event => { const href = anchor.getAttribute("href"); if (href?.startsWith("/")) { event.preventDefault(); history.pushState({}, "", href); render(); } })); document.querySelectorAll("[data-type]").forEach(button => button.addEventListener("click", () => { state.type = button.dataset.type; state.result = null; state.fileId = null; render(); })); document.querySelectorAll("[data-demo]").forEach(button => button.addEventListener("click", async () => { const example = demoExamples.find(item => item.id === button.dataset.demo); if (!example) return; state.type = example.type; state.label = example.label; state.value = example.value; state.result = null; state.fileId = null; state.demo = true; state.pipelineStep = 0; render(); await new Promise(resolve => setTimeout(resolve, 80)); runScan(); })); const toggle = document.querySelector("#demo-toggle"); if (toggle) toggle.addEventListener("change", () => { state.demo = toggle.checked; state.demoSamplesOpen = toggle.checked; state.pipelineStep = 0; render(); }); const sampleToggle = document.querySelector("#sample-toggle"); if (sampleToggle) sampleToggle.addEventListener("click", () => { state.demoSamplesOpen = !state.demoSamplesOpen; render(); }); document.querySelectorAll("[data-sample]").forEach(button => button.addEventListener("click", async () => { const example = demoExamples.find(item => item.id === button.dataset.sample); if (!example) return; state.type = example.type; state.value = example.value; state.label = example.label; state.result = null; state.fileId = null; state.demo = true; state.demoSamplesOpen = false; render(); await new Promise(resolve => setTimeout(resolve, 80)); runScan(); })); const label = document.querySelector("#label"); if (label) label.addEventListener("input", event => state.label = event.target.value); const value = document.querySelector("#value"); if (value) value.addEventListener("input", event => { state.value = event.target.value; const analyzeButton = document.querySelector("#analyze"); if (analyzeButton) analyzeButton.disabled = !state.value.trim() || state.uploading; }); const file = document.querySelector("#qr-file"); if (file) file.addEventListener("change", event => handleFile(event.target.files?.[0])); const analyzeButton = document.querySelector("#analyze"); if (analyzeButton) analyzeButton.addEventListener("click", runScan); }
async function handleFile(file) { if (!file || file.size > 5 * 1024 * 1024) { alert("Choose an image under 5 MB."); return; } state.uploading = true; render(); const reader = new FileReader(); reader.onload = async () => { try { const uploaded = await rpc("files.upload", { originalName: file.name, mimeType: file.type, dataBase64: String(reader.result) }, "POST"); state.fileId = uploaded.id; state.label = file.name; state.uploading = false; const image = new Image(); image.onload = async () => { if ("BarcodeDetector" in window) { try { const detector = new BarcodeDetector({ formats: ["qr_code"] }); const codes = await detector.detect(image); if (codes[0]?.rawValue) state.value = codes[0].rawValue; } catch {} } render(); }; image.src = String(reader.result); } catch { state.uploading = false; render(); alert("The QR upload could not be stored. The local scan still works with pasted payload text."); } }; reader.readAsDataURL(file); }
async function runScan() { const liveValue = document.querySelector("#value")?.value ?? state.value; const liveLabel = document.querySelector("#label")?.value ?? state.label; state.value = liveValue; state.label = liveLabel; if (!liveValue.trim()) { alert("Add something to inspect first."); return; } const box = document.querySelector("#scan-box"); const button = document.querySelector("#analyze"); box?.classList.add("is-scanning"); if (button) { button.disabled = true; button.innerHTML = "Scanning signal… <span class=\"spinner\">◌</span>"; } if (state.demo) { for (let step = 1; step <= 3; step++) { await new Promise(resolve => setTimeout(resolve, 360)); state.pipelineStep = step; const trace = document.querySelector(".demo-trace"); if (trace) trace.outerHTML = `<div class=\"demo-trace\"><div class=\"trace-head\"><span class=\"mono\">DEMO MODE / MODEL TRACE</span><span class=\"live-chip\">LIVE</span></div>${state.pipeline.map((item, index) => `<div class=\"trace-step ${index <= state.pipelineStep ? "done" : ""} ${index === state.pipelineStep ? "current" : ""}\"><span>${index <= state.pipelineStep ? "✓" : "0" + (index + 1)}</span><div><b>${item}</b><small>${index === 0 ? "Input received" : index === 1 ? "Domain, sender, and syntax pass" : index === 2 ? "Signals weighted against ruleset" : "Plain-language response ready"}</small></div></div>`).join("")}</div>`; } } await new Promise(resolve => setTimeout(resolve, 700)); state.result = analyze(state.type, liveValue, liveLabel); try { const saved = await rpc("scans.create", { inputType: state.type, inputLabel: state.result.label, inputContent: liveValue, score: state.result.score, verdict: state.result.verdict, summary: state.result.summary, evidence: state.result.findings.map(f => `${f.title}: ${f.detail}`), nextSteps: state.result.nextSteps }, "POST"); if (state.type === "qr" && state.fileId) { await rpc("files.linkToScan", { fileId: state.fileId, scanId: saved.id }, "POST"); } await loadData(); } catch {} render(); window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" }); }
window.addEventListener("popstate", render); loadData().finally(render);
