from pathlib import Path

path = Path('/home/ubuntu/adya-vigil-ai/client/src/main.js')
source = path.read_text()
source = source.replace('const navItems = [{ href: "/", label: "Dashboard", icon: "◉" }, { href: "/scan", label: "Scan center", icon: "⌁" }, { href: "/history", label: "Scan history", icon: "◷" }, { href: "/about", label: "About model", icon: "ⓘ" }];', 'const navItems = [{ href: "/", label: "Dashboard", icon: "◉" }, { href: "/how-it-works", label: "How it works", icon: "◇" }, { href: "/scan", label: "Scan center", icon: "⌁" }, { href: "/history", label: "Scan history", icon: "◷" }, { href: "/about", label: "About model", icon: "ⓘ" }];')
start = source.index('function scanPage() {')
end = source.index('function resultCard', start)
new_scan = r'''function scanPage() {
  const types = scanTypes.map(item => `<button data-type="${item.id}" class="type-tab ${state.type === item.id ? "selected" : ""}"><span>${item.icon}</span>${item.label}</button>`).join("");
  const trace = state.pipeline.map((step, index) => `<div class="trace-step ${index <= state.pipelineStep ? "done" : ""} ${index === state.pipelineStep ? "current" : ""}"><span>${index <= state.pipelineStep ? "✓" : "0" + (index + 1)}</span><div><b>${step}</b><small>${index === 0 ? "Input received" : index === 1 ? "Domain, sender, and syntax pass" : index === 2 ? "Signals weighted against ruleset" : "Plain-language response ready"}</small></div></div>`).join("");
  const demoTrace = state.demo ? `<div class="demo-trace"><div class="trace-head"><span class="mono">DEMO MODE / MODEL TRACE</span><span class="live-chip">LIVE</span></div>${trace}</div>` : `<div class="demo-callout"><span class="mono">MODEL VISIBILITY</span><b>Turn on demo mode to watch each check happen.</b><p>The trace is illustrative; the final score still comes from the live local ruleset.</p></div>`;
  const samplePicker = state.demo ? `<button id="sample-toggle" type="button" class="sample-toggle" aria-expanded="${state.demoSamplesOpen}"><span>⌄</span>${state.demoSamplesOpen ? "Hide demo samples" : "Show demo samples"}</button>${state.demoSamplesOpen ? `<div class="sample-picker"><div class="sample-picker-head"><span class="mono">PASTE-READY SAMPLES</span><span>2 HIGH · 2 LOW</span></div><div class="sample-grid">${demoExamples.map((example, index) => `<button type="button" class="sample-card ${example.risk}" data-sample="${example.id}"><span class="sample-card-meta"><span>${example.type.toUpperCase()} ${String(index + 1).padStart(2, "0")}</span><b>${example.risk === "high" ? "HIGH RISK" : "LOW RISK"}</b></span><span class="sample-card-value">${esc(example.value)}</span><span class="sample-card-action">Paste into field ↗</span></button>`).join("")}</div></div>` : ""}` : "";
  const fieldLabel = state.type === "url" ? "URL or domain" : state.type === "email" ? "Sender, subject, and body" : state.type === "sms" ? "Message content" : "Decoded QR payload or context";
  const qr = state.type === "qr" ? `<div class="upload-zone"><span class="upload-icon">⇧</span><div><b>${state.uploading ? "Uploading to secure storage…" : "Upload a QR image"}</b><small>PNG, JPG, WEBP, or GIF · max 5 MB</small></div><input id="qr-file" type="file" accept="image/png,image/jpeg,image/webp,image/gif" /></div>` : "";
  return shell(`<section class="page-wrap">${pageHeader("SCAN CENTER / LIVE ANALYSIS", `Check the signal<br><i>before you follow it.</i>`, "Paste a suspicious URL, email, SMS, or QR payload. ADYA VIGIL AI turns raw content into an explainable risk posture.", `<div class="header-meta"><span class="online-pill"><span class="status-dot"></span> Engine ready</span><label class="switch-row"><span>Demo trace</span><input id="demo-toggle" type="checkbox" ${state.demo ? "checked" : ""} /><span class="switch"></span></label></div>`)}<div class="scan-layout single-scan"><div class="scan-panel paper-card ${state.result ? "has-result" : ""}"><div class="panel-head"><div><span class="mono">01 / INPUT SIGNAL</span><h2>What do you want to inspect?</h2></div><span class="panel-glyph">⌬</span></div><div class="type-tabs">${types}</div><label class="field-label">Optional label <span>for scan history</span></label><input id="label" class="input" value="${esc(state.label)}" placeholder="e.g. Invoice email from unknown sender" /><div id="scan-box" class="scan-box"><div class="scan-box-grid"></div><span class="scan-target">⌁</span><span class="scan-beam"></span><label class="field-label">${fieldLabel}</label>${qr}<textarea id="value" class="textarea" placeholder="${state.type === "url" ? "https://example.com/account/verify" : "Paste the complete content here…"}">${esc(state.value)}</textarea>${samplePicker}</div><div class="scan-actions"><button id="analyze" class="button primary" ${state.uploading || !state.value.trim() ? "disabled" : ""}>${state.result ? "Run again" : "Analyze signal"} <span>↗</span></button><span class="mono">LOCAL HEURISTICS · EXPLAINABLE</span></div></div></div>${state.result ? resultCard(state.result) : ""}</section>`);
}

function howItWorksPage() {
  const stages = [
    ["01", "Capture the signal", "Paste a URL, email, SMS, or QR payload. The content is kept in this workspace while the scan runs."],
    ["02", "Inspect structure", "The model checks domains, protocols, sender context, syntax, redirects, and browser-execution markers."],
    ["03", "Weight evidence", "Each matching signal contributes a visible weight to the score instead of disappearing behind a black-box verdict."],
    ["04", "Explain the posture", "The result pairs the score with plain-language findings and a practical next-step playbook."],
  ];
  return shell(`<section class="page-wrap">${pageHeader("HOW IT WORKS / MODEL VISIBILITY", `See the signal<br><i>behind the score.</i>`, "ADYA VIGIL AI is designed to make phishing analysis understandable: inspect the structure, show the evidence, and give the user a safer next move.", `<a href="/scan" class="button primary">Open scan center <span>↗</span></a>`)}<div class="how-hero"><div>${shieldViz()}</div><div><span class="mono">LOCAL HEURISTICS · EXPLAINABLE</span><h2>Evidence, not a black box.</h2><p>The scanner uses deterministic rules to identify common phishing patterns. It does not claim that a low score proves a message is safe; it shows what the local ruleset noticed so a person can verify the context independently.</p><div class="how-pills"><span>Visible evidence</span><span>Weighted signals</span><span>Safer next steps</span></div></div></div><div class="stage-grid">${stages.map(stage => `<article class="stage-card"><span class="stage-number">${stage[0]}</span><span class="mono">MODEL STAGE</span><h3>${stage[1]}</h3><p>${stage[2]}</p></article>`).join("")}</div><div class="how-columns"><div class="paper-card"><span class="mono">SIGNALS WE CHECK</span><h2>What moves the score?</h2><div class="signal-list"><div><b>Pressure language</b><span>Urgency and forced action requests that reduce time for verification.</span></div><div><b>Credential or payment lure</b><span>Requests for passwords, codes, cards, payments, or sensitive details.</span></div><div><b>URL and redirect structure</b><span>Unencrypted destinations, risky patterns, deep subdomains, encoded values, and short links.</span></div><div><b>Weak JavaScript markers</b><span>Script-like content that may redirect users or expose browser session data.</span></div></div></div><div class="paper-card guidance-card"><span class="mono">AFTER THE SCORE</span><h2>What should the user do next?</h2><p>Pause before clicking, replying, downloading, or paying. Verify the sender or destination through a known-good channel, and report unexpected requests to the relevant provider.</p><a href="/scan" class="text-link">Run your own signal check ↗</a></div></div></section>`);
}

'''
source = source[:start] + new_scan + source[end:]
source = source.replace('function render() { const path = window.location.pathname; app.innerHTML = path === "/scan" ? scanPage() : path === "/history" ? historyPage() : path === "/about" ? aboutPage() : dashboard(); bind(); }', 'function render() { const path = window.location.pathname; app.innerHTML = path === "/scan" ? scanPage() : path === "/how-it-works" ? howItWorksPage() : path === "/history" ? historyPage() : path === "/about" ? aboutPage() : dashboard(); bind(); }')
path.write_text(source)
