from pathlib import Path

path = Path('/home/ubuntu/adya-vigil-ai/client/src/main.js')
source = path.read_text()
start = source.index('function scanPage() {')
end = source.index('function resultCard', start)
replacement = r'''function scanPage() {
  const types = scanTypes.map(item => `<button data-type="${item.id}" class="type-tab ${state.type === item.id ? "selected" : ""}"><span>${item.icon}</span>${item.label}</button>`).join("");
  const trace = state.pipeline.map((step, index) => `<div class="trace-step ${index <= state.pipelineStep ? "done" : ""} ${index === state.pipelineStep ? "current" : ""}"><span>${index <= state.pipelineStep ? "✓" : "0" + (index + 1)}</span><div><b>${step}</b><small>${index === 0 ? "Input received" : index === 1 ? "Domain, sender, and syntax pass" : index === 2 ? "Signals weighted against ruleset" : "Plain-language response ready"}</small></div></div>`).join("");
  const demoTrace = state.demo ? `<div class="demo-trace"><div class="trace-head"><span class="mono">DEMO MODE / MODEL TRACE</span><span class="live-chip">LIVE</span></div>${trace}</div>` : `<div class="demo-callout"><span class="mono">MODEL VISIBILITY</span><b>Turn on demo mode to watch each check happen.</b><p>The trace is illustrative; the final score still comes from the live local ruleset.</p></div>`;
  const sampleCards = state.demoSamplesOpen ? `<div class="sample-picker"><div class="sample-picker-head"><span class="mono">PASTE-READY SAMPLES</span><span>2 HIGH · 2 LOW</span></div><div class="sample-grid">${demoExamples.map((example, index) => `<button type="button" class="sample-card ${example.risk}" data-sample="${example.id}"><span class="sample-card-meta"><span>${example.type.toUpperCase()} ${String(index + 1).padStart(2, "0")}</span><b>${example.risk === "high" ? "HIGH RISK" : "LOW RISK"}</b></span><span class="sample-card-value">${esc(example.value)}</span><span class="sample-card-action">Paste into field ↗</span></button>`).join("")}</div></div>` : "";
  const fieldLabel = state.type === "url" ? "URL or domain" : state.type === "email" ? "Sender, subject, and body" : state.type === "sms" ? "Message content" : "Decoded QR payload or context";
  const qr = state.type === "qr" ? `<div class="upload-zone"><span class="upload-icon">⇧</span><div><b>${state.uploading ? "Uploading to secure storage…" : "Upload a QR image"}</b><small>PNG, JPG, WEBP, or GIF · max 5 MB</small></div><input id="qr-file" type="file" accept="image/png,image/jpeg,image/webp,image/gif" /></div>` : "";
  return shell(`<section class="page-wrap">${pageHeader("SCAN CENTER / LIVE ANALYSIS", `Check the signal<br><i>before you follow it.</i>`, "Paste a suspicious URL, email, SMS, or QR payload. ADYA VIGIL AI turns raw content into an explainable risk posture.", `<div class="header-meta"><span class="online-pill"><span class="status-dot"></span> Engine ready</span><label class="switch-row"><span>Demo trace</span><input id="demo-toggle" type="checkbox" ${state.demo ? "checked" : ""} /><span class="switch"></span></label></div>`)}<div class="scan-layout"><div class="scan-panel paper-card ${state.result ? "has-result" : ""}"><div class="panel-head"><div><span class="mono">01 / INPUT SIGNAL</span><h2>What do you want to inspect?</h2></div><span class="panel-glyph">⌬</span></div><div class="type-tabs">${types}</div><label class="field-label">Optional label <span>for scan history</span></label><input id="label" class="input" value="${esc(state.label)}" placeholder="e.g. Invoice email from unknown sender" /><div id="scan-box" class="scan-box"><div class="scan-box-grid"></div><span class="scan-target">⌁</span><span class="scan-beam"></span><label class="field-label">${fieldLabel}</label>${qr}<textarea id="value" class="textarea" placeholder="${state.type === "url" ? "https://example.com/account/verify" : "Paste the complete content here…"}">${esc(state.value)}</textarea><button id="sample-toggle" type="button" class="sample-toggle" aria-expanded="${state.demoSamplesOpen}"><span>⌄</span>${state.demoSamplesOpen ? "Hide demo samples" : "Show demo samples"}</button>${sampleCards}</div><div class="scan-actions"><button id="analyze" class="button primary" ${state.uploading || !state.value.trim() ? "disabled" : ""}>${state.result ? "Run again" : "Analyze signal"} <span>↗</span></button><span class="mono">LOCAL HEURISTICS · EXPLAINABLE</span></div></div><aside class="signal-board"><div class="board-visual"><img src="${HERO_IMAGE}" alt="QR code on a security analysis desk" /><div class="visual-stamp"><span class="status-dot"></span> evidence-led</div></div><div class="board-copy"><span class="mono">02 / HOW IT WORKS</span><h3>Evidence, not a black box.</h3><p>The model checks pressure language, credential requests, obfuscated destinations, weak JavaScript markers, sender context, and risky URL structure.</p><div class="check-row">✓ Every signal gets a plain-language reason</div><div class="check-row">✓ Every result ends with a safer next step</div>${demoTrace}</div></aside></div>${state.result ? resultCard(state.result) : ""}</section>`);
}

'''
path.write_text(source[:start] + replacement + source[end:])
